"""Plot a Webots or offline CSV log generated by this project."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_csv(path: Path):
    data = np.genfromtxt(path, delimiter=",", names=True, dtype=None, encoding="utf-8")
    return data


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "csv",
        nargs="?",
        default=str(Path(__file__).resolve().parents[1] / "logs" / "webots_log.csv"),
        help="CSV file to plot",
    )
    args = parser.parse_args()
    path = Path(args.csv)
    data = load_csv(path)

    # Handle both Webots and offline column names.
    time_key = "time_s" if "time_s" in data.dtype.names else "t"
    x_key = "cart_x_m" if "cart_x_m" in data.dtype.names else "x"
    th_key = "theta_rad" if "theta_rad" in data.dtype.names else "theta"
    force_key = "force_N" if "force_N" in data.dtype.names else "force"

    t = data[time_key]

    plt.figure()
    plt.plot(t, data[th_key])
    plt.axhline(0.0, linewidth=1)
    plt.xlabel("time [s]")
    plt.ylabel("pole angle [rad]")
    plt.title("Pole angle")
    plt.grid(True)

    plt.figure()
    plt.plot(t, data[x_key])
    plt.axhline(0.0, linewidth=1)
    plt.xlabel("time [s]")
    plt.ylabel("cart position [m]")
    plt.title("Cart position")
    plt.grid(True)

    plt.figure()
    plt.plot(t, data[force_key])
    plt.axhline(0.0, linewidth=1)
    plt.xlabel("time [s]")
    plt.ylabel("force [N]")
    plt.title("MPC cart force")
    plt.grid(True)

    print(f"Loaded: {path}")
    plt.show()


if __name__ == "__main__":
    main()
